repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2  # Specify the mypy version
    hooks:
      - id: mypy
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format